"""
Django settings for HT project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""




'''04/30/19 - Add support for Active Directory Log in'''
##Update LDAP and re-import users

import os

#import django_pyodbc

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@bdo*iu4%jt&a^gksnnf5m+9=xgw#6gbr*+9q6)8^1zu1m7y1)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    
    'django.contrib.auth', #used for authentication/login
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jquery',
    'django_python3_ldap',
    #'pyodbc',
    #'django_pyodbc',
    'HeatTreat',
    'Homepage',
    'rest_framework',
    'import_export',
    'AcidClean',
    'django.contrib.admin', ##This must be after 'HeatTreat' so logout process HeatTreat logged_out.html, and not Django Admin logout
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', #Used for login/ authentication
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HT.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

TIME_FORMAT = [
        
        'H:i' #22:15
        
        ]

TIME_INPUT_FORMATS = [
        
        '%H:%M'
        
        ]
LOGIN_REDIRECT_URL = '/homepage/' #goes to XYZ/homepage/
# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
        
        "django_python3_ldap.auth.LDAPBackend", ###If you want Active Directory users to be able to log in
    "django.contrib.auth.backends.ModelBackend", ###If you want Django users to be able to log in 
        ]

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "MSAEROSPACE" ##Works needed for msaerospace\username login scheme


##Can be foudn in DC2 - > Active Directory Users and Computers -> Users -> pick a user -> Attribut Editor
LDAP_AUTH_USER_FIELDS = {
    "username": "sAMAccountName", #correct
    "first_name": "givenName", #correct
    "last_name": "sn", #correct
    "email": "mail", #correct
}

LDAP_AUTH_OBJECT_CLASS = "users"
LDAP_AUTH_USER_LOOKUP_FIELDS = ('username',)



#LDAP_AUTH_URL = 'ldap://DC2.msaerospace.local:389' ## SEEMS TO BE WORKING; 
#LDAP_AUTH_URL = 'ldap://DC2:389' ## SEEMS TO BE WORKING; do not use port 389 that sends PW in the clear
LDAP_AUTH_URL = 'ldap://10.1.1.28:389' ## SEEMS TO BE WORKING; do not use port 389 that sends PW in the clear
#LDAP_AUTH_URL = 'ldap://10.1.1.29:636' ## NOT WORKING; do not use port 389 that sends PW in the clear
##From DC2 - > CMD - > dsquery user -name administrator, drop CN=administrator
#LDAP_AUTH_SEARCH_BASE = "CN=Users, DC=msaerospace,DC=local" ##This no longer works as of 05/28/19 as some users are now separated into departments
'''This will search top level active directory, parsing through all sub folders. This is the most broad search'''
LDAP_AUTH_SEARCH_BASE = "DC=msaerospace,DC=local"
#this is from 10.1.1.24 Active Directory - > Domain Controllers -> Attribute Editor
#this is from 10.1.1.24 Active Directory - > msaerospace.local side bar -> properties -> attribute editor

#LDAP_AUTH_USE_TLS=True
LDAP_AUTH_CONNECTION_USERNAME = None
LDAP_AUTH_CONNECTION_PASSWORD = None



## DC2 - > Active Director Users and Computers -> Pick a User -> Attribut Editor -> objectClass
LDAP_AUTH_OBJECT_CLASS = "organizationalPerson"

#LDAP_AUTH_CONNECT_TIMEOUT = 4
#LDAP_AUTH_RECEIVE_TIMEOUT = 4

#LOGGING = {
#    "version": 1,
#    "disable_existing_loggers": False,
#    "handlers": {
#        "console": {
#            "class": "logging.StreamHandler",
#        },
#    },
#    "loggers": {
#        "django_python3_ldap": {
#            "handlers": ["console"],
#            "level": "INFO",
#        },
#    },
#}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True ## Changed 1_24_19 to mess with time formats

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#STATIC_ROOT = r'C:\Users\stefflc\Desktop\DjangoHT\HT\static'

TEMPLATE_DIRS = (os.path.join(BASE_DIR, 'templates'), ) #Added playing with templates as views

                    
