# Generated by Django 2.1.4 on 2019-01-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0002_auto_20190107_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='VF2Cap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specTitaniumQuenchDelayMax',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
