# Generated by Django 2.1.4 on 2019-01-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0003_auto_20190115_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='TimeIn',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heattreat',
            name='dateIn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heattreat',
            name='dateOut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heattreat',
            name='timeOut',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
