# Generated by Django 2.1.4 on 2019-01-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0004_auto_20190115_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heattreat',
            old_name='TimeIn',
            new_name='timeIn',
        ),
    ]
