# Generated by Django 2.1.4 on 2019-01-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0005_auto_20190115_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnaceName', models.CharField(max_length=50)),
                ('furnaceDescription', models.CharField(max_length=50, null=True)),
                ('furnace1', models.CharField(blank=True, max_length=100, null=True)),
                ('furnace2', models.CharField(blank=True, max_length=100, null=True)),
                ('furnace3', models.CharField(blank=True, max_length=100, null=True)),
                ('furnace4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
