# Generated by Django 2.1.4 on 2019-01-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0006_furnaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutiontreatspecs',
            name='VFMinusTimeTol',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='solutiontreatspecs',
            name='VFPHTSetPointHigh',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='solutiontreatspecs',
            name='VFPHTSetPointLow',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='solutiontreatspecs',
            name='VFPHTSetPointPref',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='solutiontreatspecs',
            name='VFPlusTimeTol',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='solutiontreatspecs',
            name='VFSoak',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='solutiontreatspecs',
            name='VFSoakPref',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='solutiontreatspecs',
            name='specTempSetPointPref',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutiontreatspecs',
            name='specUniformityTolPref',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
