# Generated by Django 2.1.4 on 2019-01-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0008_solutiontreatspecs_specsoaktimepref'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='couponInit',
            field=models.CharField(max_length=5, null=True, verbose_name='Initials'),
        ),
    ]
