# Generated by Django 2.1.4 on 2019-01-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0010_auto_20190122_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreat',
            name='partsCleaned',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=3, null=True),
        ),
    ]
