# Generated by Django 2.1.4 on 2019-01-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0011_auto_20190122_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreat',
            name='partsCleaned',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('YES', 'YES'), ('NO', 'NO')], default='Yes', max_length=3, null=True),
        ),
    ]
