# Generated by Django 2.1.4 on 2019-01-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0012_auto_20190122_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreat',
            name='quenchMethod',
            field=models.CharField(blank=True, choices=[('OIL', 'Oil'), ('OIL', 'OIL'), ('OIL', 'oil'), ('GFC', 'GFC'), ('GFC', 'gfc'), ('GFC', 'Gfc'), ('WATER', 'Water'), ('WATER', 'water'), ('WATER', 'WATER'), ('AIR', 'Air'), ('AIR', 'air')], default=' ', max_length=5, null=True),
        ),
    ]
