# Generated by Django 2.1.4 on 2019-01-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0013_auto_20190122_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreat',
            name='cleaningReq',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('YES', 'YES'), ('NO', 'NO')], default='Yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='quenchMethod',
            field=models.CharField(blank=True, choices=[('OIL', 'Oil'), ('OIL', 'OIL'), ('oil', 'OIL'), ('GFC', 'GFC'), ('GFC', 'gfc'), ('GFC', 'Gfc'), ('WATER', 'Water'), ('WATER', 'water'), ('WATER', 'WATER'), ('AIR', 'Air'), ('AIR', 'air')], default=' ', max_length=5, null=True),
        ),
    ]
