# Generated by Django 2.1.4 on 2019-01-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0014_auto_20190124_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heattreat',
            name='timeIn',
        ),
    ]
