# Generated by Django 2.1.4 on 2019-01-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0015_remove_heattreat_timein'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='timeIn',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
