# Generated by Django 2.1.4 on 2019-02-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0018_polarchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specCleaning',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
