# Generated by Django 2.1.4 on 2019-02-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0020_auto_20190211_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='loadNumber',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='heattreat',
            name='numLoads',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
