# Generated by Django 2.1.4 on 2019-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0021_auto_20190211_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreat',
            name='couponInit',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Initials'),
        ),
    ]
