# Generated by Django 2.1.4 on 2019-02-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0022_auto_20190212_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='VFMinusTimeTol',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heattreat',
            name='VFPHTSetPoint',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heattreat',
            name='VFPlusTimeTol',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heattreat',
            name='VFSoak',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='quenchMethod',
            field=models.CharField(blank=True, choices=[('Oil', 'OIL'), ('OIL', 'OIL'), ('oil', 'OIL'), ('GFC', 'GFC'), ('gfc', 'GFC'), ('Gfc', 'GFC'), ('Water', 'WATER'), ('water', 'WATER'), ('WATER', 'WATER'), ('Air', 'AIR'), ('air', 'AIR'), (' ', ' ')], default=' ', max_length=5, null=True),
        ),
    ]
