# Generated by Django 2.1.4 on 2019-02-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0026_auto_20190215_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiallist',
            name='field1',
        ),
        migrations.AddField(
            model_name='materiallist',
            name='ageMaterial',
            field=models.BooleanField(blank=True, max_length=100, null=True, verbose_name='Is this an age material?'),
        ),
        migrations.AddField(
            model_name='materiallist',
            name='annealMaterial',
            field=models.BooleanField(blank=True, max_length=100, null=True, verbose_name='Is this an anneal material?'),
        ),
        migrations.AddField(
            model_name='materiallist',
            name='hardenMaterial',
            field=models.BooleanField(blank=True, max_length=100, null=True, verbose_name='Is this a harden material?'),
        ),
        migrations.AddField(
            model_name='materiallist',
            name='normalMaterial',
            field=models.BooleanField(blank=True, max_length=100, null=True, verbose_name='Is this a normalize material?'),
        ),
        migrations.AddField(
            model_name='materiallist',
            name='solutionMaterial',
            field=models.BooleanField(blank=True, max_length=100, null=True, verbose_name='Is this a solution treat material?'),
        ),
        migrations.AddField(
            model_name='materiallist',
            name='temperMaterial',
            field=models.BooleanField(blank=True, max_length=100, null=True, verbose_name='Is this a temper material?'),
        ),
    ]
