# Generated by Django 2.1.4 on 2019-02-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0027_auto_20190219_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiallist',
            name='ageMaterial',
            field=models.BooleanField(blank=True, default=False, max_length=100, null=True, verbose_name='Is this an age material?'),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='annealMaterial',
            field=models.BooleanField(blank=True, default=False, max_length=100, null=True, verbose_name='Is this an anneal material?'),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='hardenMaterial',
            field=models.BooleanField(blank=True, default=False, max_length=100, null=True, verbose_name='Is this a harden material?'),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='normalMaterial',
            field=models.BooleanField(blank=True, default=False, max_length=100, null=True, verbose_name='Is this a normalize material?'),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='solutionMaterial',
            field=models.BooleanField(blank=True, default=False, max_length=100, null=True, verbose_name='Is this a solution treat material?'),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='temperMaterial',
            field=models.BooleanField(blank=True, default=False, max_length=100, null=True, verbose_name='Is this a temper material?'),
        ),
    ]
