# Generated by Django 2.1.4 on 2019-02-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0028_auto_20190219_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specLoadTC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specPartsCleanedAfterQuench',
            field=models.CharField(blank=True, default='No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specSoakMinusTimeTol',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specTempBeforeQuenchHigh',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specTempBeforeQuenchLow',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
