# Generated by Django 2.1.4 on 2019-02-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0031_auto_20190221_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcert',
            name='dateOut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
