# Generated by Django 2.1.4 on 2019-02-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0032_printcert_dateout'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcert',
            name='dateCertCreated',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='dateCertModified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
