# Generated by Django 2.1.4 on 2019-02-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0033_auto_20190222_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcert',
            name='SoakTimeLoad11',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='SoakTimeLoad12',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='SoakTimeLoad13',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='SoakTimeLoad14',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='SoakTimeLoad15',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='SoakTimeLoad16',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='quantityLoad11',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='quantityLoad12',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='quantityLoad13',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='quantityLoad14',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='quantityLoad15',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='quantityLoad16',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTempLoad11',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTempLoad12',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTempLoad13',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTempLoad14',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTempLoad15',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTempLoad16',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeEndLoad11',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeEndLoad12',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeEndLoad13',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeEndLoad14',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeEndLoad15',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeEndLoad16',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeStartLoad11',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeStartLoad12',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeStartLoad13',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeStartLoad14',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeStartLoad15',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='soakTimeStartLoad16',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='weightLoad11',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='weightLoad12',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='weightLoad13',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='weightLoad14',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='weightLoad15',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printcert',
            name='weightLoad16',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
