# Generated by Django 2.1.4 on 2019-03-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0035_auto_20190225_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='tempSetPointPref',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Preferred Temp. for Work Order'),
        ),
    ]
