# Generated by Django 2.1.4 on 2019-03-06 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0036_heattreat_tempsetpointpref'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='soakTimePref',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
