# Generated by Django 2.1.4 on 2019-03-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0037_heattreat_soaktimepref'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='operatorID',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operators',
            name='operatorName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
