# Generated by Django 2.1.4 on 2019-03-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0038_auto_20190306_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreat',
            name='PWABatchControl',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='PWAMCL',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='TMQTenPurge',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='agitReq',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='goodCond',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='partialPressure',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='ageMaterial',
            field=models.NullBooleanField(default=False, max_length=100, verbose_name='Is this an age material?'),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='annealMaterial',
            field=models.NullBooleanField(default=False, max_length=100, verbose_name='Is this an anneal material?'),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='hardenMaterial',
            field=models.NullBooleanField(default=False, max_length=100, verbose_name='Is this a harden material?'),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='normalMaterial',
            field=models.NullBooleanField(default=False, max_length=100, verbose_name='Is this a normalize material?'),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='solutionMaterial',
            field=models.NullBooleanField(default=False, max_length=100, verbose_name='Is this a solution treat material?'),
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='temperMaterial',
            field=models.NullBooleanField(default=False, max_length=100, verbose_name='Is this a temper material?'),
        ),
        migrations.AlterField(
            model_name='printcert',
            name='PWABatchControl',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='printcert',
            name='PWAMCL',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='printcert',
            name='certSaved',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printcert',
            name='coupons',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specQuenchAir',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specQuenchGFC',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specQuenchOil',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specQuenchWater',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specTMQ1',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specTMQ2',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specTMQ3',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specVF1',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='solutiontreatspecs',
            name='specVF2',
            field=models.NullBooleanField(),
        ),
    ]
