# Generated by Django 2.1.4 on 2019-03-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0039_auto_20190321_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreat',
            name='PO',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='customer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='partsCleaned',
            field=models.CharField(default='Yes', max_length=3, null=True),
        ),
    ]
