# Generated by Django 2.1.4 on 2019-03-28 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0040_auto_20190326_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='operatorDone',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='heattreat',
            name='operatorDoneDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='quenchMethod',
            field=models.CharField(blank=True, choices=[('OIL', 'OIL'), ('GFC', 'GFC'), ('WATER', 'WATER'), ('AIR', 'AIR'), (' ', ' ')], default=' ', max_length=5, null=True),
        ),
    ]
