# Generated by Django 2.1.4 on 2019-03-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0041_auto_20190328_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcert',
            name='overrideSafeguard',
            field=models.BooleanField(default=False, verbose_name='If yes, allows any input'),
        ),
    ]
