# Generated by Django 2.1.4 on 2019-04-01 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0042_printcert_overridesafeguard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreat',
            name='PO',
            field=models.CharField(max_length=250, verbose_name='Purchase Order'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='TMQTenPurge',
            field=models.NullBooleanField(verbose_name='10 Minute Purge performed for TMQ furnace? '),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='VF1Cap',
            field=models.BooleanField(default=False, verbose_name='VF1 Spec. Capacity'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='VFVacPressure',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='VF(Vacuum Furnace) Vacuum Pressure, in microns'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='WOop',
            field=models.IntegerField(blank=True, verbose_name='Work Order Operation'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='WQuenchDelay',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Titanium Quench Delay'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='agitReq',
            field=models.NullBooleanField(verbose_name='Is Agitation Required'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='channelOne',
            field=models.IntegerField(blank=True, null=True, verbose_name='First Thermocouple Channel#'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='channelTwo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Second Thermocouple Channel#'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='cleaningReq',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('YES', 'YES'), ('NO', 'NO')], default='Yes', max_length=3, null=True, verbose_name='Is cleaning required before heat treat?'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='coupons',
            field=models.BooleanField(default=True, verbose_name='Were Coupons Used?'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='dateIn',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Heat Treat Start'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='dateTimeIn',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and Time of Heat Treat start'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='dateTimeOut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and Time out'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='furnaceNo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Furnace Number used for Heat Treat'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='goodCond',
            field=models.NullBooleanField(verbose_name='Are Parts in Good Condition?'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='heatNumber',
            field=models.CharField(max_length=20, verbose_name='HEAT lot Number'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='loadNumber',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Heat Treat Load Number'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Is this TTPI locked, preventing further revision?'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='numLoads',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Number of Loads'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='numPans',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Pans'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='operatorDone',
            field=models.BooleanField(blank=True, default=False, verbose_name='Has the operator completed their work?'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='operatorDoneDateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Time operator completed worked'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='operatorIn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Operator who began heat treat'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='partNumber',
            field=models.CharField(max_length=100, verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='partsCleaned',
            field=models.CharField(default='Yes', max_length=3, null=True, verbose_name='Parts Cleaned after quench'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='quantityLot',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantity parts per heat treat lot'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='quenchMethod',
            field=models.CharField(blank=True, choices=[('OIL', 'OIL'), ('GFC', 'GFC'), ('WATER', 'WATER'), ('AIR', 'AIR'), (' ', ' ')], default=' ', max_length=5, null=True, verbose_name='Quench Method'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='soakTimeEnd',
            field=models.TimeField(blank=True, null=True, verbose_name='Soak time end'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='soakTimeStart',
            field=models.TimeField(blank=True, null=True, verbose_name='Some time begin'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='specNumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='Specification Numbe associated with TTPI'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='timeIn',
            field=models.TimeField(blank=True, null=True, verbose_name='Time of Heat Treat Start'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='uniformityTol',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Soak temperature +/- tolerance'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='visInspComplete',
            field=models.BooleanField(default=False, verbose_name='Visual Inspection Completed?'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='weightLot',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight per heat treat lot'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='workOrder',
            field=models.CharField(max_length=50, verbose_name='Work Order'),
        ),
    ]
