# Generated by Django 2.1.4 on 2019-04-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0043_auto_20190401_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='certCreated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operators',
            name='operatorInitials',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='operators',
            name='userActive',
            field=models.BooleanField(default=True),
        ),
    ]
