# Generated by Django 2.1.4 on 2019-04-22 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0044_auto_20190408_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='WQuenchDelaySpec',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Titanium Quench Delay allowed for this order, based on thickness'),
        ),
        migrations.AddField(
            model_name='heattreat',
            name='overrideSoakTime',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='heattreat',
            name='overrideSoakTimePlusTol',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operators',
            name='canReviewTTPI',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='WQuenchDelay',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Titanium Quench Delay, in seconds'),
        ),
    ]
