# Generated by Django 2.1.4 on 2019-04-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0045_auto_20190422_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreat',
            name='operatorDoneDateTime',
            field=models.DateTimeField(blank=True, verbose_name='Time operator completed worked'),
        ),
        migrations.AlterField(
            model_name='heattreat',
            name='partsCleaned',
            field=models.CharField(blank=True, default='No', max_length=3, null=True, verbose_name='Parts Cleaned after quench'),
        ),
    ]
