# Generated by Django 2.1.4 on 2019-04-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0046_auto_20190425_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreat',
            name='operatorDoneDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time operator completed worked'),
        ),
    ]
