# Generated by Django 2.0.3 on 2019-09-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatTreat', '0047_auto_20190425_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreat',
            name='postItNote',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
